#!/bin/bash

[[ -f .gitmodules ]] && git submodule update --init
[[ -f composer.json ]] && composer install

if [[ -f yarn.lock ]]; then
  yarn
elif [[ -f package.json ]]; then
  npm install
fi

[[ -f bower.json ]] && bower install | xargs echo

exit 0

# vim: ft=sh
